#!/usr/bin/env bash

DOTFILES_ROOT=$(pwd -P)

source $DOTFILES_ROOT/scripts/logger

link_file() {
  local src=$1 dst=$2
  ln -s $src $dst
  success "Linked $src to $dst"
}

install_dotfiles() {
  info "Installing dotfiles..."

  for src in $(find -H "$DOTFILES_ROOT" -name "*.symlink" -not -path "*.git*")
  do
    dst="$HOME/.$(basename "${src%.*}")"
    link_file "$src" "$dst"
  done
}

setup_gitconfig() {
  if ! [ -f git/gitconfig.symlink ]
  then
    info "Setting up gitconfig..."

    user " - Enter your github name:"
    read -e git_authorname
    user " - Enter your github email:"
    read -e git_authoremail

    sed -e "s/AUTHORNAME/$git_authorname/g" -e "s/AUTHOREMAIL/$git_authoremail/g" git/gitconfig.symlink.example > git/gitconfig.symlink
  fi
}

setup_gitconfig
install_dotfiles