#!/usr/bin/env bash

source "$DOTFILES_ROOT"/scripts/logger

install() {
    which $1 &> /dev/null

    if [ $? -ne 0 ]
    then
        info "Installing: ${1}..."
        sudo sh -c "$2"
    else
        info "Already installed: ${1}"
    fi
}

sudo apt update
sudo apt -y upgrade

for script_loc in $(find "$DOTFILES_ROOT" -name "install.sh")
do
    
    install "$(basename $(dirname $script_loc))" "$script_loc"
done
