#!/usr/bin/env bash

DOTFILES_ROOT=$(pwd -P)

source "$DOTFILES_ROOT"/scripts/logger

install() {
        info "Installing: ${1}..."
        sh -c "$2"
}

info "Attempting to update and upgrade packages..."
sudo apt update
sudo apt -y upgrade

for script_loc in $(find "$DOTFILES_ROOT" -name "install.sh")
do
    if output=$(which "$(basename $(dirname $script_loc))");
    then
        info "Already installed: $(basename $(dirname $script_loc))"
        continue
    fi

    user "Run ${script_loc}?, select an option:\n\
    [y]es, [n]o?"
    read -n 1 action
    if [ "$action" = "y" ];
    then
        info "Running ${script_loc}..."
        install "$(basename $(dirname $script_loc))" "$script_loc"
    fi
done
